// EPaper marketing site — entry script.
//
// Every page arrives with its content already in the HTML (generated by
// src/site/content.ts at build time), so this script renders nothing. It
// registers the custom elements, measures the chrome and wires the two
// interactive pages. A visitor with JavaScript disabled still gets every
// page, all their text and working navigation.
import '../../../packages/epaper-components/src/styles/tokens.css';
import '../../../packages/epaper-components/src/styles/base.css';
import '../../../packages/epaper-components/src/styles/components.css';
import './site.css';
// Imported as a value, not just for its side effect: the bundler would
// otherwise elide the module and leave <e-site-pager> unregistered.
import { ESitePager } from './pager';
import { esc } from '../../../packages/epaper-components/src/core/dom';
import { type ComponentCategory } from './data';

const $ = <T extends HTMLElement = HTMLElement>(sel: string): T | null =>
  document.querySelector(sel);

/* --------------------------------------------------------------------- *
 * Chrome
 * --------------------------------------------------------------------- */

/**
 * Publishes the measured height of the sticky header and the fixed footbar as
 * `--site-header-h` / `--site-footbar-h` on <html>.
 *
 * Both bars are out of flow, and the header in particular changes height when
 * the nav wraps onto its own row below 900px. The CSS defaults are close
 * enough for first paint; these keep the section min-height, the bottom
 * padding and the scroll offset exact at every width.
 */
function trackChromeHeights(): void {
  const header = $('#site-header');
  const footbar = $('#site-footbar');
  const root = document.documentElement;

  const sync = (): void => {
    if (header) root.style.setProperty('--site-header-h', `${Math.round(header.offsetHeight)}px`);
    if (footbar) {
      root.style.setProperty('--site-footbar-h', `${Math.round(footbar.offsetHeight)}px`);
    }
  };
  sync();

  if (typeof ResizeObserver === 'function') {
    const ro = new ResizeObserver(sync);
    if (header) ro.observe(header);
    if (footbar) ro.observe(footbar);
  } else {
    window.addEventListener('resize', sync);
  }
}

function wireChrome(): void {
  trackChromeHeights();

  // Below 900px the nav is a horizontal scroll strip and the current page can
  // start out beyond its right edge.
  const current = $<HTMLAnchorElement>('#site-nav a[aria-current="page"]');
  current?.scrollIntoView({ block: 'nearest', inline: 'nearest' });

  // Registers the key bindings. The element is inert until it upgrades.
  void ESitePager;
}

/* --------------------------------------------------------------------- *
 * Page 3 — component search and category filter
 * --------------------------------------------------------------------- */
function wireComponentFilter(): void {
  const grid = $('#comp-grid');
  const countEl = $('#comp-count');
  const search = $('#comp-search');
  const seg = $('#comp-cat');
  if (!grid) return;

  let cat: ComponentCategory | 'all' = 'all';
  let q = '';

  const apply = (): void => {
    let visible = 0;
    for (const tile of grid.querySelectorAll<HTMLElement>('.site-comp__tile')) {
      const name = tile.dataset['name'] ?? '';
      const tag = tile.dataset['tag'] ?? '';
      const tcat = tile.dataset['cat'] ?? '';
      const matchCat = cat === 'all' || tcat === cat;
      const matchQ = q === '' || name.includes(q) || tag.includes(q);
      if (matchCat && matchQ) {
        tile.removeAttribute('hidden');
        visible++;
      } else {
        tile.setAttribute('hidden', '');
      }
    }
    if (countEl) countEl.textContent = `${visible} components`;
  };

  search?.addEventListener('e-input', (e) => {
    q = ((e as CustomEvent<{ value: string }>).detail.value || '').trim().toLowerCase();
    apply();
  });
  seg?.addEventListener('e-change', (e) => {
    cat = (e as CustomEvent<{ value: ComponentCategory | 'all' }>).detail.value;
    apply();
  });
}

/* --------------------------------------------------------------------- *
 * Page 4 — showcase form
 * --------------------------------------------------------------------- */
function wireShowcase(): void {
  // The form is re-mounted every time the user switches tabs (e-tabs replaces
  // its panel innerHTML on activate), so the listener lives on the container.
  const tabs = $('#showcase-tabs');
  const result = $('#showcase-form-result');
  if (!tabs) return;

  tabs.addEventListener('e-submit', (e) => {
    const form = (e as CustomEvent<{ form: HTMLFormElement }>).detail.form;
    if (!result) return;
    const name = String(new FormData(form).get('name') || '(unnamed)');
    result.innerHTML = `<e-result status="success"
        title="Thanks, ${esc(name)}"
        description="Your form was captured locally."></e-result>`;
  });
}

/* --------------------------------------------------------------------- *
 * Boot
 * --------------------------------------------------------------------- */
function boot(): void {
  wireChrome();

  // Only three routes have behaviour, and they need the full element
  // registry. Load it after first paint so the critical path stays short —
  // and skip it entirely everywhere else, which includes every guide, recipe
  // and the FAQ: those are plain markup by design.
  const route = document.body.dataset['route'] ?? '/';
  const needsElements = route === '/components/' || route === '/showcase/' || route === '/install/';
  if (!needsElements) return;

  const hydrate = (): void => {
    void import('../../../packages/epaper-components/src/index').then(() => {
      if (route === '/components/') wireComponentFilter();
      if (route === '/showcase/') wireShowcase();
    });
  };

  const ric = (
    window as Window & {
      requestIdleCallback?: (cb: () => void, opts?: { timeout: number }) => number;
    }
  ).requestIdleCallback;
  if (typeof ric === 'function') ric(hydrate, { timeout: 1500 });
  else requestAnimationFrame(() => setTimeout(hydrate, 0));
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', boot, { once: true });
} else {
  boot();
}
