// Generates dist/elements.d.ts with HTMLElementTagNameMap augmentation
// from dist/custom-elements.json. Run AFTER `cem analyze`.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const cemPath = resolve(root, 'dist/custom-elements.json');
const outPath = resolve(root, 'dist/elements.d.ts');

if (!existsSync(cemPath)) {
  console.error(`[gen-tag-map] ${cemPath} not found. Run "npm run analyze" first.`);
  process.exit(1);
}

const cem = JSON.parse(readFileSync(cemPath, 'utf8'));

/** @type {Array<{ tag: string; className: string; modulePath: string }>} */
const entries = [];

for (const mod of cem.modules ?? []) {
  const exports = mod.exports ?? [];
  const declarations = mod.declarations ?? [];
  // Map declaration name -> tagName via custom-element-definition exports.
  const definitions = exports.filter((e) => e.kind === 'custom-element-definition');
  for (const def of definitions) {
    const tag = def.name;
    const className = def.declaration?.name;
    if (!tag || !className) continue;
    // Make sure the class declaration exists in this module (or any module).
    const decl =
      declarations.find((d) => d.name === className) ??
      cem.modules.flatMap((m) => m.declarations ?? []).find((d) => d.name === className);
    if (!decl) continue;
    entries.push({ tag, className, modulePath: mod.path });
  }
}

if (entries.length === 0) {
  console.warn('[gen-tag-map] No custom elements found in CEM.');
}

// Group imports by module path. The published package re-exports everything from
// the bundle entry point ("epaper"), but for the .d.ts we import from the source
// modules so types stay accurate even before the bundle is built.
const byModule = new Map();
for (const e of entries) {
  // Strip "src/" prefix and ".ts" extension; .d.ts will live in dist/, source
  // .d.ts files are emitted alongside (tsc --declaration into dist/).
  // Easier: import from the package barrel "../" relative to dist? We use the
  // bundle's type entry which re-exports all classes.
  if (!byModule.has('../dist/index')) byModule.set('../dist/index', []);
  byModule.get('../dist/index').push(e.className);
}

// Simpler & more robust: import everything from the package's own type entry.
// Since this file lives in dist/elements.d.ts, sibling import is "./index.js".
const classNames = [...new Set(entries.map((e) => e.className))].sort();
const importLine = `import type { ${classNames.join(', ')} } from './index.js';`;

const mapLines = entries
  .slice()
  .sort((a, b) => a.tag.localeCompare(b.tag))
  .map((e) => `    '${e.tag}': ${e.className};`)
  .join('\n');

const banner = `// AUTO-GENERATED by scripts/gen-tag-map.mjs — do not edit by hand.
// Run "npm run analyze" to regenerate.
`;

const content = `${banner}
${importLine}

declare global {
  interface HTMLElementTagNameMap {
${mapLines}
  }
}

export {};
`;

writeFileSync(outPath, content, 'utf8');
console.log(`[gen-tag-map] Wrote ${entries.length} tags -> ${outPath}`);

// Wire the augmentation into the package's main types entry so consumers get
// it automatically when they `import` from "epaper".
const indexDts = resolve(root, 'dist/index.d.ts');
if (existsSync(indexDts)) {
  const ref = '/// <reference path="./elements.d.ts" />';
  const current = readFileSync(indexDts, 'utf8');
  if (!current.includes(ref)) {
    writeFileSync(indexDts, `${ref}\n${current}`, 'utf8');
    console.log(`[gen-tag-map] Injected reference into ${indexDts}`);
  }
}
